### ISSUE TITLE
make polling interval configurable

### ISSUE THREAD

**Issue by tw4452852** [telegex/telegex#26]
Right now this interval is hardcoded as `35ms`, it would be nice to make it configurable.

https://github.com/telegex/telegex/blob/4c72daddad1c185d3c4eeed056897c0210e96ee4/lib/telegex/polling/handler.ex#L112

**Comment by Hentioe** [comment]
Very good suggestion, I will add related configuration soon

**Comment by Hentioe** [comment]
This is a bug, that ignored the `interval` field in the configuration. It has been fixed and relevant documentation has been added: https://hexdocs.pm/telegex/1.1.1/Telegex.Polling.Config.html
