### ISSUE TITLE
Running multiple bots using Telegex?

### ISSUE THREAD

**Issue by TwistingTwists** [telegex/telegex#27]
`config :telegex, token: "<BOT_TOKEN>"`

Can I specify one token per bot ? I might have to run 2-3 bots.

**Comment by Hentioe** [comment]
At present, Telegex can only support a single bot, because many of my projects have relied on this library before, so it is still the case after the revision. But I have plans to support multiple bots, probably version `2.0`. Currently you can deploy each bot as an instance.

**Comment by TwistingTwists** [comment]
Thanks for the explanation!
