### ISSUE TITLE
Feature request: support multiple method calls in payload

### ISSUE THREAD

**Issue by tw4452852** [telegex/telegex#30]
Right now, we only support one method call in the response's payload (`%{payload: %{method: xxx ...}`). Can we support multiple method calls upon an update, something like: `%{payload: [%{method: xxx ...}, %{method: xxx ...} ...]}`.

I do see this is feasible from Telegram FAQ (https://core.telegram.org/bots/faq#how-can-i-make-requests-in-response-to-updates).

**Comment by Hentioe** [comment]
Great request, I will implement this part soon. However, regarding calling the method in the response, I currently only implement it in the chain-related features (passing the `payload` in the context) and have not written any documentation. The documentation for this part may not be available until later.

**Comment by Hentioe** [comment]
I initially thought I was missing something, but it doesn't seem like I was. I've tried returning a payload as an array of method call parameters, but without success. It may not be considered a valid response by the Telegram Bot server.

**Comment by tw4452852** [comment]
The Telegram Bot server doesn't support multiple calls in a response. My initial thought is to call these methods when chains are over.

**Comment by Hentioe** [comment]
The reason for returning method calls in a `payload` is that webhook supports responding to a single method call, which avoids the overhead of manually calling the API once. If you include multiple method calls in a `payload`, parsing the payload list and calling them loses the benefits of a `payload` and makes it difficult to handle errors.
