### ISSUE TITLE
License of the project

### ISSUE THREAD

**Issue by JoshuaDietz** [telegex/telegex#31]
Hi,

The library looks very good and I would like to use it in a project of mine but what's currently holding me back is that there's no license defined for it so I don't know what I am allowed to use it for. Could you clarify by choosing and adding a license?

Thank you very much!

**Comment by Hentioe** [comment]
Hello, I have released `v1.4.2` which contains the MIT license file.

**Comment by JoshuaDietz** [comment]
Thank you very much for the quick reply and the great license choice! Looking forward to using your library!
