### ISSUE TITLE
Plans for implementing client capabilities?

### ISSUE THREAD

**Issue by webdeb** [telegex/telegex#34]
Hi, first of all very good job!

My question is, do you plan to implement client functionality into it?
Like Gramjs or Telethon?

Thanks in advance!

**Comment by Hentioe** [comment]
If you're talking about MTProto (or other TDLib-provided functionality), this library won't implement it. It's just a standard robotics framework.

**Comment by webdeb** [comment]
Got it, can it fetch public user&channel information, as well as downloading the profile images of it? Then this would be sufficient.

**Comment by Hentioe** [comment]
Reference: https://core.telegram.org/bots/api
